version: "3"

services:
  db:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=example
      - POSTGRES_HOST=db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jobyatp -d mts" ]
      interval: 10s
      timeout: 35s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
